/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.tristanjl.nb.externalcommmands;

import org.openide.util.NbPreferences;

final class ExternalCommandsPanel extends javax.swing.JPanel
{

    private final ExternalCommandsOptionsPanelController controller;

    ExternalCommandsPanel(ExternalCommandsOptionsPanelController controller)
    {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        commandlabel1 = new javax.swing.JLabel();
        command1 = new javax.swing.JFormattedTextField();
        commandlabel2 = new javax.swing.JLabel();
        commandlabel3 = new javax.swing.JLabel();
        commandlabel4 = new javax.swing.JLabel();
        commandlabel5 = new javax.swing.JLabel();
        commandlabel6 = new javax.swing.JLabel();
        commandlabel7 = new javax.swing.JLabel();
        commandlabel8 = new javax.swing.JLabel();
        commandlabel9 = new javax.swing.JLabel();
        commandlabel10 = new javax.swing.JLabel();
        command2 = new javax.swing.JFormattedTextField();
        command3 = new javax.swing.JFormattedTextField();
        command4 = new javax.swing.JFormattedTextField();
        command5 = new javax.swing.JFormattedTextField();
        command6 = new javax.swing.JFormattedTextField();
        command7 = new javax.swing.JFormattedTextField();
        command8 = new javax.swing.JFormattedTextField();
        command9 = new javax.swing.JFormattedTextField();
        command10 = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel1, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel1.text")); // NOI18N

        command1.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command1.text")); // NOI18N
        command1.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command1.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel2, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel3, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel4, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel5, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel6, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel7, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel8, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel9, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commandlabel10, org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel10.text")); // NOI18N

        command2.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command2.text")); // NOI18N
        command2.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command2.toolTipText")); // NOI18N

        command3.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command3.text")); // NOI18N
        command3.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command3.toolTipText")); // NOI18N

        command4.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command4.text")); // NOI18N
        command4.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command4.toolTipText")); // NOI18N

        command5.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command5.text")); // NOI18N
        command5.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command5.toolTipText")); // NOI18N

        command6.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command6.text")); // NOI18N
        command6.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command6.toolTipText")); // NOI18N

        command7.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command7.text")); // NOI18N
        command7.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command7.toolTipText")); // NOI18N

        command8.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command8.text")); // NOI18N
        command8.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command8.toolTipText")); // NOI18N

        command9.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command9.text")); // NOI18N
        command9.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command9.toolTipText")); // NOI18N

        command10.setText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command10.text")); // NOI18N
        command10.setToolTipText(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.command10.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commandlabel1)
                    .addComponent(commandlabel7)
                    .addComponent(commandlabel8)
                    .addComponent(commandlabel9)
                    .addComponent(commandlabel6)
                    .addComponent(commandlabel10)
                    .addComponent(commandlabel5)
                    .addComponent(commandlabel2)
                    .addComponent(commandlabel4)
                    .addComponent(commandlabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(command10, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command9, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command8, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command7, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command5, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command6, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(command1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(commandlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(10, Short.MAX_VALUE)
                        .addComponent(command1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandlabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(command3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(commandlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(commandlabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(command10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(commandlabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        commandlabel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel1.AccessibleContext.accessibleName")); // NOI18N
        commandlabel6.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ExternalCommandsPanel.class, "ExternalCommandsPanel.commandlabel6.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    void load()
    {
        command1.setText(NbPreferences.forModule(ExternalCommands.class).get("command1", ""));
        command2.setText(NbPreferences.forModule(ExternalCommands.class).get("command2", ""));
        command3.setText(NbPreferences.forModule(ExternalCommands.class).get("command3", ""));
        command4.setText(NbPreferences.forModule(ExternalCommands.class).get("command4", ""));
        command5.setText(NbPreferences.forModule(ExternalCommands.class).get("command5", ""));
        command6.setText(NbPreferences.forModule(ExternalCommands.class).get("command6", ""));
        command7.setText(NbPreferences.forModule(ExternalCommands.class).get("command7", ""));
        command8.setText(NbPreferences.forModule(ExternalCommands.class).get("command8", ""));
        command9.setText(NbPreferences.forModule(ExternalCommands.class).get("command9", ""));
        command10.setText(NbPreferences.forModule(ExternalCommands.class).get("command10", ""));
    }

    void store()
    {
        NbPreferences.forModule(ExternalCommands.class).put("command1", command1.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command2", command2.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command3", command3.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command4", command4.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command5", command5.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command6", command6.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command7", command7.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command8", command8.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command9", command9.getText());
        NbPreferences.forModule(ExternalCommands.class).put("command10", command10.getText());
    }

    boolean valid()
    {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField command1;
    private javax.swing.JFormattedTextField command10;
    private javax.swing.JFormattedTextField command2;
    private javax.swing.JFormattedTextField command3;
    private javax.swing.JFormattedTextField command4;
    private javax.swing.JFormattedTextField command5;
    private javax.swing.JFormattedTextField command6;
    private javax.swing.JFormattedTextField command7;
    private javax.swing.JFormattedTextField command8;
    private javax.swing.JFormattedTextField command9;
    private javax.swing.JLabel commandlabel1;
    private javax.swing.JLabel commandlabel10;
    private javax.swing.JLabel commandlabel2;
    private javax.swing.JLabel commandlabel3;
    private javax.swing.JLabel commandlabel4;
    private javax.swing.JLabel commandlabel5;
    private javax.swing.JLabel commandlabel6;
    private javax.swing.JLabel commandlabel7;
    private javax.swing.JLabel commandlabel8;
    private javax.swing.JLabel commandlabel9;
    // End of variables declaration//GEN-END:variables
}
